@baseUrl = http://localhost:3001/api

# Get info
GET {{baseUrl}}/info

###

# Get all persons
GET {{baseUrl}}/persons

###

# Get person with ID 67783879eaa663c547f34a6a
GET {{baseUrl}}/persons/67783879eaa663c547f34a6a

###

# Get person with ID 9999 (not found test)
GET {{baseUrl}}/persons/9999

###

# Delete person with ID 6778389c2875e1aded7cfa8f
DELETE {{baseUrl}}/persons/6778389c2875e1aded7cfa8f

###

# Create new person
POST {{baseUrl}}/persons
Content-Type: application/json

{
    "name": "Mario Bianchi",
    "number": "+39 3271234567"
}

###

# Create new person, bad request (missing number)
POST {{baseUrl}}/persons
Content-Type: application/json

{
    "name": "Mario Rossi"
}

###

# Create new person, bad request (missing name)
POST {{baseUrl}}/persons
Content-Type: application/json

{
    "number": "+39 3271234567"
}

###

# Create new person, bad request (name already exists)
POST {{baseUrl}}/persons
Content-Type: application/json

{
    "name": "Arto Hellas", 
    "number": "040-123456"
}

###

# Update number of person with ID 677857f13a98faf086a569f9
PUT {{baseUrl}}/persons/677857f13a98faf086a569f9
Content-Type: application/json

{
    "name": "Mario Bianchi",
    "number": "111111111"
}